/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEFVAR = 5;
  /** RegularExpression Id. */
  int DEFPROC = 6;
  /** RegularExpression Id. */
  int JUMP = 7;
  /** RegularExpression Id. */
  int WALK = 8;
  /** RegularExpression Id. */
  int LEAP = 9;
  /** RegularExpression Id. */
  int TURN = 10;
  /** RegularExpression Id. */
  int TURNTO = 11;
  /** RegularExpression Id. */
  int DROP = 12;
  /** RegularExpression Id. */
  int GET = 13;
  /** RegularExpression Id. */
  int GRAB = 14;
  /** RegularExpression Id. */
  int LETGO = 15;
  /** RegularExpression Id. */
  int NOP = 16;
  /** RegularExpression Id. */
  int CARDINALDIR = 17;
  /** RegularExpression Id. */
  int DIRECTION = 18;
  /** RegularExpression Id. */
  int WALKDIR = 19;
  /** RegularExpression Id. */
  int TURNDIR = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int ELSE = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int REPEAT = 24;
  /** RegularExpression Id. */
  int TIMES = 25;
  /** RegularExpression Id. */
  int FACING = 26;
  /** RegularExpression Id. */
  int CAN = 27;
  /** RegularExpression Id. */
  int NOT = 28;
  /** RegularExpression Id. */
  int MOV = 29;
  /** RegularExpression Id. */
  int RIGHT = 30;
  /** RegularExpression Id. */
  int PUT = 31;
  /** RegularExpression Id. */
  int PICK = 32;
  /** RegularExpression Id. */
  int POP = 33;
  /** RegularExpression Id. */
  int GO = 34;
  /** RegularExpression Id. */
  int HOP = 35;
  /** RegularExpression Id. */
  int BALLOONS = 36;
  /** RegularExpression Id. */
  int CHIPS = 37;
  /** RegularExpression Id. */
  int NUM = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int NAME = 40;
  /** RegularExpression Id. */
  int LETTER = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"defVar\"",
    "\"defProc\"",
    "\"jump\"",
    "\"walk\"",
    "\"leap\"",
    "\"turn\"",
    "\"turnto\"",
    "\"drop\"",
    "\"get\"",
    "\"grab\"",
    "\"letGo\"",
    "\"nop\"",
    "<CARDINALDIR>",
    "<DIRECTION>",
    "<WALKDIR>",
    "\"around\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"repeat\"",
    "\"times\"",
    "\"facing\"",
    "\"can\"",
    "\"not\"",
    "\"Mov\"",
    "\"RightOld\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUM>",
    "<DIGIT>",
    "<NAME>",
    "<LETTER>",
    "\"{\"",
    "\"}\"",
    "\"()\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\":\"",
  };

}
